export const TODOS_DATA = 'TODOS_DATA';
export const TODOS_DATA_LOADING = 'TODOS_DATA_LOADING';
export const TODOS_FORM_LOADING = 'TODOS_FORM_LOADING';
export const TODOS_FORM_OPENED = 'TODOS_FORM_OPENED';
